[Service]
EnvironmentFile=/etc/default/dotmac-alloy
Environment="CONFIG_FILE=/etc/alloy/config.alloy"
Environment="CUSTOM_ARGS=--server.http.listen-addr=127.0.0.1:12345 --disable-reporting"
SupplementaryGroups=adm systemd-journal docker
NoNewPrivileges=yes
PrivateTmp=yes
ProtectHome=yes
ProtectSystem=strict
ReadWritePaths=/var/lib/alloy
ReadOnlyPaths=/var/log/journal
ReadOnlyPaths=/run/log/journal
ReadOnlyPaths=/var/lib/docker
UMask=0027
