"""Deterministic rendering of the desired state into evaluator configuration.

The single authority for what the control plane's configuration BYTES are
(``.dotmac/standards-profile.json`` names this module's
:func:`render_control_plane` as the decision interface). Everything else —
the CLI, the promotion lane, the rehearsal — is an adapter that calls it and
writes or compares the result.

Two properties matter more than elegance here:

* **Determinism.** Same desired state, same bytes, every time, on every
  machine. No timestamps, no hostname, no iteration over a set, no locale-
  dependent sort. ``make render-check`` is a byte comparison, so a renderer
  that is merely *usually* stable turns the gate into noise.
* **Wholeness.** One call produces the entire file tree. A renderer that emits
  one file per call invites a caller to update two of three files and stage a
  configuration nobody has ever seen.
"""

from __future__ import annotations

import hashlib
from collections.abc import Mapping
from pathlib import Path
from typing import TypeAlias

from .model import (
    DesiredState,
    Federation,
    Label,
    Receiver,
    ScrapeJob,
    SecretFile,
)
from .yaml_emit import YamlValue, emit

__all__ = [
    "ALERTMANAGER_CONFIG",
    "COMPOSE_FILE",
    "PROMETHEUS_CONFIG",
    "RenderedTree",
    "differences",
    "render_control_plane",
    "tree_digest",
    "write_tree",
]

RenderedTree: TypeAlias = tuple[tuple[str, str], ...]

PROMETHEUS_CONFIG = "prometheus/prometheus.yml"
ALERTMANAGER_CONFIG = "alertmanager/alertmanager.yml"
COMPOSE_FILE = "docker-compose.yml"

# Paths INSIDE the containers. Fixed rather than configurable: they are an
# implementation detail of the rendered compose file, which mounts the release
# directory at these locations. Making them knobs would let the config and the
# mount disagree, which is unobservable until an evaluator starts with no rules.
_PROMETHEUS_ETC = "/etc/prometheus"
_ALERTMANAGER_ETC = "/etc/alertmanager"
_RULES_GLOB = f"{_PROMETHEUS_ETC}/rules/*.yml"
_TEMPLATES_GLOB = f"{_ALERTMANAGER_ETC}/templates/*.tmpl"
# One host directory of secret files is mounted into BOTH containers, at a
# different path in each. Deriving the reference from the same constant the
# mount uses is what stops a credential path pointing into the other
# service's tree — a mistake that renders and validates cleanly and then
# silently delivers nothing.
# `:?` rather than `:-`: there is no sensible default release directory, and
# a bare ${VAR} would resolve to the empty string, which for a mount source
# means the container starts with nothing mounted and no error.
_RELEASE = "${OBSERVABILITY_RELEASE:?release directory is required}"
_PROMETHEUS_SECRETS = f"{_PROMETHEUS_ETC}/secrets"
_ALERTMANAGER_SECRETS = f"{_ALERTMANAGER_ETC}/secrets"

_HEADER = (
    "GENERATED by `dotmac-observability render` — do not edit.",
    "Source of truth: inventory/, bundles/ and routing/ in dotmac_observability.",
    "`make render-check` compares these bytes against a fresh render and fails on drift.",
)


def _port(listen: str) -> str:
    return listen.rsplit(":", 1)[1]


def _labels_mapping(labels: tuple[Label, ...]) -> dict[str, YamlValue]:
    return {label.name: label.value for label in labels}


def _secret_path(directory: str, secret: SecretFile) -> str:
    return f"{directory}/{secret.file_name}"


def _scrape_config(job: ScrapeJob) -> dict[str, YamlValue]:
    config: dict[str, YamlValue] = {
        "job_name": job.job,
        "scheme": job.scheme,
        "metrics_path": job.metrics_path,
    }
    if job.scrape_interval is not None:
        config["scrape_interval"] = job.scrape_interval
    if job.scrape_timeout is not None:
        config["scrape_timeout"] = job.scrape_timeout
    if job.credential is not None:
        # A FILE reference. The token itself is placed on the host from
        # OpenBao by the deployment and never appears in this repository.
        config["bearer_token_file"] = _secret_path(_PROMETHEUS_SECRETS, job.credential)
    static: dict[str, YamlValue] = {"targets": list(job.endpoints)}
    if job.labels:
        static["labels"] = _labels_mapping(job.labels)
    config["static_configs"] = [static]
    return config


def _federation_config(federation: Federation) -> dict[str, YamlValue]:
    config: dict[str, YamlValue] = {
        "job_name": federation.name,
        # The upstream's labels win: this plane is importing the upstream's
        # view, not relabelling it into its own.
        "honor_labels": True,
        "scheme": federation.source.scheme,
        "metrics_path": federation.source.path,
        "params": {"match[]": list(federation.match)},
    }
    if federation.scrape_interval is not None:
        config["scrape_interval"] = federation.scrape_interval
    if federation.source.credential is not None:
        config["bearer_token_file"] = _secret_path(
            _PROMETHEUS_SECRETS, federation.source.credential
        )
    static: dict[str, YamlValue] = {"targets": [federation.source.endpoint]}
    if federation.labels:
        static["labels"] = _labels_mapping(federation.labels)
    config["static_configs"] = [static]
    # AGENTS.md rule 9. `up` and `scrape_*` describe the UPSTREAM's opinion of
    # its own targets. Imported under their own names they join this plane's
    # health series, and a central `up == 0` then pages on something this plane
    # neither owns nor can repair. Renaming makes the two populations
    # impossible to conflate in a query.
    config["metric_relabel_configs"] = [
        {
            "source_labels": ["__name__"],
            "regex": "(up|scrape_.+)",
            "target_label": "__name__",
            "replacement": f"{federation.rename_prefix}${{1}}",
        }
    ]
    return config


def _prometheus(state: DesiredState) -> str:
    plane = state.control_plane
    scrape_configs: list[YamlValue] = []
    for target_set in state.targets:
        for job in target_set.jobs:
            scrape_configs.append(_scrape_config(job))
    for federation in state.federations:
        scrape_configs.append(_federation_config(federation))

    document: dict[str, YamlValue] = {
        "global": {
            "scrape_interval": plane.scrape_interval,
            "scrape_timeout": plane.scrape_timeout,
            "evaluation_interval": plane.evaluation_interval,
            "external_labels": _labels_mapping(plane.external_labels),
        },
        # A glob over the release's rules directory, not a list of files. The
        # staged release decides which bundles are present; a hand-kept file
        # list here would be a second, silently divergent answer to that.
        "rule_files": [_RULES_GLOB],
        "alerting": {
            "alertmanagers": [
                {
                    "static_configs": [
                        {"targets": [f"alertmanager:{_port(plane.alertmanager.listen)}"]}
                    ]
                }
            ]
        },
        "scrape_configs": scrape_configs,
    }
    return emit(document, header=_HEADER)


_INTEGRATION_KEYS: Mapping[str, tuple[str, str, str | None]] = {
    # kind -> (alertmanager block, credential-file field, destination field)
    "telegram": ("telegram_configs", "bot_token_file", "chat_id"),
    "email": ("email_configs", "auth_password_file", "to"),
    "webhook": ("webhook_configs", "url_file", None),
    "slack": ("slack_configs", "api_url_file", "channel"),
}


def _receiver_config(receiver: Receiver) -> dict[str, YamlValue]:
    config: dict[str, YamlValue] = {"name": receiver.name}
    grouped: dict[str, list[YamlValue]] = {}
    for integration in receiver.integrations:
        block, credential_field, destination_field = _INTEGRATION_KEYS[integration.kind]
        entry: dict[str, YamlValue] = {
            credential_field: _secret_path(_ALERTMANAGER_SECRETS, integration.credential),
            "send_resolved": integration.send_resolved,
        }
        if destination_field is not None and integration.destination is not None:
            # Telegram's chat id is a NUMBER in Alertmanager's schema; quoted it
            # is silently rejected at config load, which presents as a receiver
            # that simply never delivers.
            if integration.kind == "telegram":
                entry[destination_field] = int(integration.destination)
            else:
                entry[destination_field] = integration.destination
        grouped.setdefault(block, []).append(entry)
    for block, entries in grouped.items():
        config[block] = entries
    return config


def _route_config(state: DesiredState) -> dict[str, YamlValue]:
    children: list[YamlValue] = []
    for route in state.routes:
        child: dict[str, YamlValue] = {
            "receiver": route.receiver,
            "matchers": list(route.matchers),
        }
        if route.keep_going:
            child["continue"] = True
        if route.group_by is not None:
            child["group_by"] = list(route.group_by)
        if route.group_wait is not None:
            child["group_wait"] = route.group_wait
        if route.group_interval is not None:
            child["group_interval"] = route.group_interval
        if route.repeat_interval is not None:
            child["repeat_interval"] = route.repeat_interval
        children.append(child)

    defaults = state.defaults
    root: dict[str, YamlValue] = {
        "receiver": defaults.receiver,
        "group_by": list(defaults.group_by),
        "group_wait": defaults.group_wait,
        "group_interval": defaults.group_interval,
        "repeat_interval": defaults.repeat_interval,
    }
    if children:
        root["routes"] = children
    return root


def _alertmanager(state: DesiredState) -> str:
    plane = state.control_plane
    globals_block: dict[str, YamlValue] = {"resolve_timeout": plane.resolve_timeout}
    if plane.smtp is not None:
        globals_block["smtp_smarthost"] = plane.smtp.smarthost
        globals_block["smtp_from"] = plane.smtp.sender
        globals_block["smtp_require_tls"] = plane.smtp.require_tls
        if plane.smtp.auth_username is not None:
            globals_block["smtp_auth_username"] = plane.smtp.auth_username
    document: dict[str, YamlValue] = {
        "global": globals_block,
        "templates": [_TEMPLATES_GLOB],
        "route": _route_config(state),
    }
    if state.inhibitions:
        document["inhibit_rules"] = [
            {
                "source_matchers": list(rule.source_matchers),
                "target_matchers": list(rule.target_matchers),
                # Never omitted. An inhibition without `equal` suppresses the
                # target everywhere rather than only where the cause applies,
                # which is the commonest way an inhibition silences an
                # unrelated outage.
                "equal": list(rule.equal),
            }
            for rule in state.inhibitions
        ]
    document["receivers"] = [_receiver_config(receiver) for receiver in state.receivers]
    return emit(document, header=_HEADER)


def _compose(state: DesiredState) -> str:
    plane = state.control_plane
    prometheus_port = _port(plane.prometheus.listen)
    alertmanager_port = _port(plane.alertmanager.listen)
    document: dict[str, YamlValue] = {
        "name": f"observability-{plane.environment}",
        "services": {
            "prometheus": {
                # Digest, not tag. A tag is a mutable pointer; the receipt has
                # to be able to say exactly what ran.
                "image": f"{plane.prometheus.image}@{plane.prometheus.digest}",
                "restart": "${OBSERVABILITY_RESTART:-unless-stopped}",
                "user": "${PROMETHEUS_USER:-65534:65534}",
                "command": [
                    f"--config.file={_PROMETHEUS_ETC}/prometheus.yml",
                    "--storage.tsdb.path=/prometheus",
                    "--storage.tsdb.retention.time=${PROMETHEUS_RETENTION:-90d}",
                    f"--web.listen-address=0.0.0.0:{prometheus_port}",
                    # Reload over the lifecycle API, so activation never has to
                    # recreate the container and lose the scrape window.
                    "--web.enable-lifecycle",
                ],
                "ports": [f"${{PROMETHEUS_LISTEN:-{plane.prometheus.listen}}}:{prometheus_port}"],
                # DIRECTORY mounts, read-only. A single-file bind mount detaches
                # its inode on rename, which is precisely why the host became
                # append-only-by-hand and unowned (AGENTS.md rule 2).
                "volumes": [
                    f"{_RELEASE}/prometheus:{_PROMETHEUS_ETC}:ro",
                    f"${{OBSERVABILITY_SECRETS:-{plane.secrets_dir}}}:{_PROMETHEUS_ETC}/secrets:ro",
                    "prometheus_data:/prometheus",
                ],
            },
            "alertmanager": {
                "image": f"{plane.alertmanager.image}@{plane.alertmanager.digest}",
                "restart": "${OBSERVABILITY_RESTART:-unless-stopped}",
                "user": "${ALERTMANAGER_USER:-65534:65534}",
                "command": [
                    f"--config.file={_ALERTMANAGER_ETC}/alertmanager.yml",
                    "--storage.path=/alertmanager",
                    f"--web.listen-address=0.0.0.0:{alertmanager_port}",
                ],
                "ports": [
                    f"${{ALERTMANAGER_LISTEN:-{plane.alertmanager.listen}}}:{alertmanager_port}"
                ],
                "volumes": [
                    f"{_RELEASE}/alertmanager:{_ALERTMANAGER_ETC}:ro",
                    f"${{OBSERVABILITY_SECRETS:-{plane.secrets_dir}}}:{_ALERTMANAGER_ETC}/secrets:ro",
                    "alertmanager_data:/alertmanager",
                ],
            },
        },
        "volumes": {"prometheus_data": {}, "alertmanager_data": {}},
    }
    return emit(document, header=_HEADER)


def render_control_plane(state: DesiredState) -> RenderedTree:
    """Render every configuration file for ``state``, in a fixed order."""
    return (
        (PROMETHEUS_CONFIG, _prometheus(state)),
        (ALERTMANAGER_CONFIG, _alertmanager(state)),
        (COMPOSE_FILE, _compose(state)),
    )


def tree_digest(tree: RenderedTree) -> str:
    """A digest over paths AND contents, recorded in every promotion receipt.

    Both halves are hashed: a rendering that moved a file without changing any
    byte inside it is still a different deployment.
    """
    digest = hashlib.sha256()
    for path, text in tree:
        digest.update(path.encode("utf-8"))
        digest.update(b"\0")
        digest.update(text.encode("utf-8"))
        digest.update(b"\0")
    return digest.hexdigest()


def write_tree(tree: RenderedTree, destination: Path) -> None:
    for path, text in tree:
        target = destination / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8")


def differences(tree: RenderedTree, destination: Path) -> tuple[str, ...]:
    """Paths whose committed bytes disagree with a fresh render.

    Includes files that are missing on disk and files on disk that the
    renderer no longer produces — a stale file left behind still gets mounted
    into the evaluator.
    """
    drifted: list[str] = []
    rendered = dict(tree)
    for path, text in tree:
        target = destination / path
        if not target.is_file():
            drifted.append(f"{path} (missing)")
        elif target.read_text(encoding="utf-8") != text:
            drifted.append(f"{path} (differs)")
    if destination.is_dir():
        for existing in sorted(destination.rglob("*")):
            if not existing.is_file():
                continue
            relative = existing.relative_to(destination).as_posix()
            if relative not in rendered:
                drifted.append(f"{relative} (unexpected)")
    return tuple(drifted)
